# Generated by Django 5.2.6 on 2025-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='default_room.webp', max_length=500, null=True, upload_to=''),
        ),
    ]
